### ISSUE TITLE
Package version of the download not up-to-date #30

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/bmsc-app#1]
Original ticket: https://github.com/INWT/mpi-constraint-estimation-app/issues/30

Regarding
> - [ ] BMSC

I do only have the link to a beta version

The app seems to be up-to-date with the `main` version 0.5.8 in the repository mpi-constraint-estimation-**app**:
- https://isomemoapp.com/app/constraint-estimation-app-beta
- https://github.com/INWT/mpi-constraint-estimation-app/blob/main/DESCRIPTION

However, if one downloads the package BMSC (not the app) it has version 0.2.1. In the repo we have version 0.7.7 in the repository **mpi-constraint-estimation**: https://github.com/INWT/MPI-constraint-estimation/blob/master/DESCRIPTION

_Originally posted by @arunge in https://github.com/INWT/mpi-iso-app/issues/259#issuecomment-1017494631_

@jroachell15 I confused the two apps, it is BMSC where the downloadable package has an old version number.

I could not identify the corresponding job on Jenkins...

**Comment by arunge** [comment]
There was confusion since we have a newer version of the BMSC package on our site, but there is an older version that was published on cran:
- https://rdrr.io/cran/BMSC/
- https://github.com/cran/BMSC

The link of the webpage points to the version published on cran.

Now, we have the option to install the newest version from this repository here, since it is open source now: https://github.com/Pandora-IsoMemo/drat with

```
options(repos = c(getOption("repos"), PANDORA = "https://Pandora-IsoMemo.github.io/drat/"))
install.packages("BMSC")
```
