### ISSUE TITLE
Error box at the end of model calculation

### ISSUE THREAD

**Issue by AdamBIzdebski** [Pandora-IsoMemo/bmsc-app#25]
I get this at the very end of the calculation:
simpleWarning in !is.null(mustExclude) && mustExclude != "": 'length(x) = 94 > 1' in coercion to 'logical(1)'
when I click OK on this error  box, the results display and look the way they should

Use numerical and categorical indep vars, interaction 2 and exponent 2, with most interactive vars except four of them excluded

Happy to share my data file and exact settings if needed

**Comment by arunge** [comment]
@AdamBIzdebski I could reproduce this behavior with example data. This was a warning that occurs if there is a vector instead of a value in an if-condition (which should not be the case). I [fixed the condition](https://github.com/Pandora-IsoMemo/bmsc/commit/af917742581af904bc5e4e345fcf62adca49d655) and the warning should disappear with BMSC App version 23.07.0.2. Could you please check your results? Possibly the excluded variables not have been excluded explicitly.

Thanks for reporting this, and in case of any other issues, please let me know!

**Comment by AdamBIzdebski** [comment]
Wonderful, thank you!Adam—-dr hab. Adam IzdebskiIndependent Research Group Leader“Palaeo-Science & History”Research Group Max Planck Institute of Geoanthropology Jena, GermanyInstitute of HistoryJagiellonian University in Krakow PolandWiadomość napisana przez Antonia Runge ***@***.***> w dniu 25.07.2023, o godz. 17:02:﻿
@AdamBIzdebski I could reproduce this behavior with example data. This was a warning that occurs if there is a vector instead of a value in an if-condition (which should not be the case). I fixed the condition and the warning should disappear with BMSC App version 23.07.0.2. Could you please check your results? Possibly the excluded variables not have been excluded explicitly.
Thanks for reporting this, and in case of any other issues, please let me know!
