### ISSUE TITLE
BMSC install

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/bmsc-app#8]
Hi again, as I mentioned previously the BMSC install is too complicated. In the instructions, I had requested a simple install (similar to other apps). However, there is an additional issue. The install instructions are for Windows. What about other systems?

**Comment by jroachell15** [comment]
@isomemo 

We hear your concern. Please understand the complexity of BMSC app, it requires some extra software that the typical `install.packages` won't be able to download. These are very complex dependencies that the R environment itself cannot produce. So we ask for your input to choose either 1)cDocker option or 2)publish it on CRAN for easy user installation (which will most likely take up to a long time because there are a lot of functions. 

It appears that it's not recommended by CRAN to publish ShinyApps: https://community.rstudio.com/t/can-i-publish-a-shiny-app-package-on-cran-that-requires-a-database-connection/92735/3

- so we thought the best is to use the docker option. It's really not hard at all. It takes a few minutes to install Docker and then just run the relevant commands and we have a virtual environment for the app to start. It's so simple that I think it beats the R-studio approach, which requires 4 steps (install R, R--studio, install other relevant dependencies, varies between apps and take more time), the Docker requires just 2 steps . The docker is even better for people who don't know how to code. The user doesn't even need to open R-studio. Maybe we should have a screenshare and I show you how easy this is.

**Comment by jroachell15** [comment]
This is also on hold until Sebastian comes back from vacation

**Comment by isomemo** [comment]
@jroachell15 @mgross Please discuss this with Marcus. this was supposed to be an R app with a separate Shiny interface on top.

@mgross what would be the instructions to install this locally (without using Docker)?

**Comment by arunge** [comment]
We added installation instructions for docker also for the [BMSC app](https://github.com/Pandora-IsoMemo/bmsc-app/wiki/Local-install-instructions). Despite the complex dependencies for the BMSC app, we cannot offer more here and hope that the installation works for the most cases.
